require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.0
  Exclude:
    - 'vendor/**/*'
    - 'lib/cloudkeeper_grpc/*'

Metrics/LineLength:
  Max: 135

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'lib/cloudkeeper/entities/appliance.rb'
    - 'lib/cloudkeeper/nginx/http_server.rb'

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'lib/cloudkeeper/entities/conversions.rb'

Metrics/ClassLength:
  Max: 120
  Exclude:
    - 'lib/cloudkeeper/cli.rb'

Metrics/ClassLength:
  Max: 125
  Include:
    - 'lib/cloudkeeper/managers/appliance_manager.rb'

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Max: 3

RSpec/NestedGroups:
  Max: 4
  Include:
    - 'spec/cloudkeeper/backend_connector_spec.rb'

RSpec/SubjectStub:
  Exclude:
    - 'spec/cloudkeeper/backend_connector_spec.rb'

Metrics/ParameterLists:
  Exclude:
    - 'lib/cloudkeeper/entities/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '*.gemspec'
    - 'lib/cloudkeeper/entities/appliance.rb'
    - 'lib/cloudkeeper/entities/image_list.rb'
    - 'lib/cloudkeeper/grpc/*'
