require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.0

Metrics/LineLength:
    Max: 135

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Exclude:
    - 'lib/cloudkeeper/entities/appliance.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/cloudkeeper/entities/appliance.rb'

Style/StructInheritance:
  Exclude:
    - 'lib/cloudkeeper/entities/*.rb'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/cloudkeeper/entities/image_spec.rb'
    - 'spec/cloudkeeper/entities/image_list_spec.rb'
    - 'spec/cloudkeeper/entities/appliance_spec.rb'
    - 'spec/cloudkeeper/managers/image_list_manager_spec.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/cloudkeeper/entities/image_list_spec.rb'
    - 'spec/cloudkeeper/entities/appliance_spec.rb'
    - 'spec/cloudkeeper/managers/image_list_manager_spec.rb'

RSpec/NestedGroups:
  MaxNesting: 3

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '*.gemspec'
