AllCops:
  TargetRubyVersion: 2.0

Metrics/LineLength:
    Max: 135

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Exclude:
    - 'lib/cloudkeeper/entities/appliance.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/cloudkeeper/entities/appliance.rb'

Style/StructInheritance:
  Exclude:
    - 'lib/cloudkeeper/entities/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '*.gemspec'
