require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.0

Metrics/LineLength:
    Max: 135

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Exclude:
    - 'lib/cloudkeeper/entities/appliance.rb'
    - 'lib/cloudkeeper/backend_connector.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/cloudkeeper/entities/appliance.rb'
    - 'lib/cloudkeeper/nginx/http_server.rb'

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  MaxNesting: 3

RSpec/NestedGroups:
  MaxNesting: 4
  Include:
    - 'spec/cloudkeeper/backend_connector_spec.rb'

RSpec/SubjectStub:
  Exclude:
    - 'spec/cloudkeeper/backend_connector_spec.rb'

Metrics/ParameterLists:
  Exclude:
    - 'lib/cloudkeeper/entities/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '*.gemspec'
    - 'lib/cloudkeeper/entities/appliance.rb'
    - 'lib/cloudkeeper/entities/image_list.rb'
    - 'lib/cloudkeeper/grpc/*'
