sudo: false

language: ruby
rvm:
  - ruby-head
  - 2.2
  - 2.1
  - 2.0
  - 1.9

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 1.9
fast_finish: true

before_install: gem install bundler -v 1.13.0
