cloudkeeper:
  image-lists: # List of image lists
  ca-dir: /etc/grid-security/certificates/
  image-dir: /var/spool/cloudkeeper/images/
  binaries:
    qemu-img: /usr/bin/qemu-img # Path to qemu-img binary (image conversion)
  logging:
    level: ERROR # Logging level
    file: /var/log/cloudkeeper/cloudkeeper.log # File to write log to. To turn off file logging leave this field empty.
  debug: false # Debug mode
